stages:
  - build
  - deploy
maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -DskipTests"
  after_script: "cp -r target/* ~/jboss-eap/"
  artifacts:
    paths:
      - target/*.jar
